Add Smiley to dummy app, an example of a compound component
mjanjic01/ember-konva pull request #3
Opened 2021-07-16 02:08 UTC by kagemusha

2021-07-16 08:36 UTC, mjanjic01 requested changes

2021-07-16 08:36 UTC, mjanjic01 commented on tests/dummy/app/components/smiley/component.js
> +  @tracked radius = this.args.radius;
These properties don't need to be tracked, as they are only assigned once and never change.
In the getters you can use `this.args.x` directly

2021-07-16 08:36 UTC, mjanjic01 commented on tests/dummy/app/components/smiley/template.hbs
> +<@parent.Text @text={{@name}} @x={{nameX}} @width={{nameWidth}} @y={{nameY}} @align="center" />
To make the entire thing draggable you would need to have a single Konva node to group them together, therefor a `Group`.

Suggestion:
```suggestion
<@parent.Group @draggable={{true}} as |G|>
  <G.Circle @x={{@x}} @y={{@y}} @radius={{@radius}} @fill={{@back}} @stroke={{@fore}} @strokeWidth={{2}} />
  <G.Circle @x={{leftEyeX}} @y={{eyeY}} @radius={{4}} @fill={{@fore}} />
  <G.Circle @x={{rightEyeX}} @y={{eyeY}} @radius={{4}} @fill={{@fore}} />
  <G.Arc @x={{@x}} @y={{mouthY}} @rotation={{70}} @innerRadius={{40}} @outerRadius={{43}} @angle={{40}} @fill={{@fore}} />
  <G.Text @text={{@name}} @x={{nameX}} @width={{nameWidth}} @y={{nameY}} @align="center" />
</@parent.Group>
```

Note the `@draggable` is moved from the first circle and onto the group

2021-07-16 08:36 UTC, mjanjic01 commented on package.json
> -  "peerDependencies": {},
Also add konva versions `>=7.1.4` (the earliest version I tested with) into the peer dependencies.
So you can provide your own konva version in the project consuming this addon.
```
"peerDependencies": {
  "konva": ">=7.1.4"
}
```

2021-07-16 15:50 UTC, kagemusha commented
made edits.  let me know if all good

2021-07-18 14:07 UTC, mjanjic01 commented
Looks good 👍

2021-07-18 14:07 UTC, merged

2021-07-19 14:39 UTC, kagemusha commented
awesome and thanks for authoring this addon